[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30"
softbuffer = "0.4"
yarden = { path = "../../Yarden" }
ffmpeg-sidecar = "2.0.0"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3
