[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg = { package = "ffmpeg-next", version = "7" }
winit = "0.28.1"
winit_input_helper = "0.14"
softbuffer = "0.3.4"
yarden = { path = "../../Yarden" }
rodio = "0.19.0"
